### ISSUE TITLE
Functionality suggestion - when in a certain type of product category

### ISSUE THREAD

**Issue by schmitty5011** [schmitty5011/F18Team3#1]
On a product page, such as guitars, I think we should add functionality to enhance the experience of that page. I think that next to the link that brings you to the product page, there should be either a picture of some description of the price. This way it helps the user choose which one they want to look at without going to the page to decide. If there was a picture they could decide based on that. OR next to the product page link there could be a price description that either says "their price" (Save: "save amount) or it could not include the price they pay and could just say (Save: "save amount") but I think the actual price would be good to include there so they can choose the product they want to view based on the price right on the product category page.

**Comment by cngamba** [comment]
Rahil did the updates. I move his style from inline to main.css 

Feedback requested.

**Comment by schmitty5011** [comment]
My feedback is that the picture is great. I think we should add a parenthetical next to the link that says (Save: "save amount") so the user can choose which link to click based on how much money they would save on that product in the form of a discount. Again, this is mentioned in the new issue I have posted
