### ISSUE TITLE
Suggestion for cart

### ISSUE THREAD

**Issue by schmitty5011** [schmitty5011/F18Team3#2]
On the cart page, instead of the Return to: "Basses" (or whatever the most recent page was, I think it should say Go to: and then have links for each of the category pages because that way the user won't have to go back to the home page in order to get to other product category pages.

**Comment by cngamba** [comment]
This is fixed by having the sidebar and the navigation bar in all pages!

**Comment by schmitty5011** [comment]
This is great! As I say in the new issue I posted, I think we should try to remove the redundant link that appears in the cart.
