### ISSUE TITLE
Visual Issue

### ISSUE THREAD

**Issue by schmitty5011** [schmitty5011/F18Team3#3]
I think the header "My Guitar Shop" should look a lot better. I think we should center it and give it a different color and/or effect to make it better on the eyes.

**Comment by cngamba** [comment]
Please provide comment for the new header look and feel.

**Comment by schmitty5011** [comment]
I apologize. I am at a final presentation for MA710 but I will be able to work on the Web application after.

Sent from my iPhone

On Dec 7, 2018, at 2:32 PM, cngamba <notifications@github.com<mailto:notifications@github.com>> wrote:


Please provide comment for the new header look and feel.

**Comment by schmitty5011** [comment]
See new issue "Great New Header!"
